# -*- coding: utf-8 -*-
"""First AI LLM Prompts with OpenAI and Langchain

Automatically generated by Colab.

!pip install openai

!pip install langchain

import os
os.environ["OPENAI_API_KEY"]="YOUR API KEY"

!pip install langchain-community

import os
from langchain.llms import OpenAI

# Set the environment variable within the same cell
os.environ["OPENAI_API_KEY"] = "key"

# Instantiate the OpenAI object with the API key
llm = OpenAI(temperature=0.9, openai_api_key=os.environ["OPENAI_API_KEY"])

text= "Create a baseball team name that would be great for MLB Expansion"
print(llm(text))

from langchain.prompts import PromptTemplate

prompt_template_baseball_team= PromptTemplate(
    input_variable=["city,colour"],
    template="Create a baseball team name that would be great for MLB Expansion in {city} with primary colour {colour}"
)

print(llm(prompt_template_baseball_team.format(city="Chicago",colour="Red")))

prompt_template_baseball_team.save("prompt_template_baseball_team.json")

from langchain.prompts import load_prompt

from langchain.prompts import load_prompt

# Load the prompt template from the saved file
loaded_prompt = load_prompt("prompt_template_baseball_team.json")

# Now you can use loaded_prompt
print(loaded_prompt.format(city="Chicago", colour="Red"))

def generate_baseball_team_name(city,colour):
  llm=OpenAI(temperature=0.9)

  prompt_template_baseball_team= PromptTemplate(
    input_variable=["city,colour"],
    template="Create a baseball team name that would be great for MLB Expansion in {city} with primary colour {colour}"
)

  baseballchain= LLMChain(llm=llm,prompt=prompt_template_baseball_team)
  response =baseballchain({"city":city,"colour":colour})

  return response["text"]

from langchain.chains import LLMChain

print(generate_baseball_team_name("Chicago","Red"))



